### ISSUE TITLE
Playground engine: Generate and inject secrets on startup

### ISSUE THREAD

**Issue by iximiuz** [iximiuz/labs#1]
Need a config like:

```
playground:
  name: <name>
  secrets:
     FOO: {fixed-string}
     BAR: {random():<len>}
  machines:
    - name: node-01
      secrets:
        FOO: /run/secrets/iximiuz/foo
        BAR: /run/secrets/iximiuz/bar
    - name: node-02
      secrets:
         BAR: /run/secrets/iximiuz/bar
```
