### ISSUE TITLE
Support running tasks on multiple machines (and maybe multiple users?)

### ISSUE THREAD

**Issue by sagikazarmark** [iximiuz/labs#11]
```yaml
init_something:
  name: init_something
  machine:
    - node-01
    - node-02
    - node-03
  init: true
  user: laborant
  run: ...
```

```yaml
init_something:
  name: init_something
  machine:
    - node-01
    - node-02
    - node-03
  init: true
  user:
    - root
    - laborant
  run: ...
```
