### ISSUE TITLE
Bug: Missing machine leads to 500 error

### ISSUE THREAD

**Issue by sagikazarmark** [iximiuz/labs#12]
When using a custom playground in a tutorial, removing a machine that is present (and has init tasks) in the playground leads to 500 errors.

Proposed solution: filter tasks from the playground based on the merged machine list and remove tasks that don't have the referenced machine present.

(Probably the same should be applied to tabs)

How to reproduce:
1. Create a new tutorial using this playground: https://labs.iximiuz.com/playgrounds/openbao-vault-cluster-playground-0c4ec7ce
2. Override tabs and machines:
```yaml
  machines:
    - name: node-01
      users:
        - name: root
        - name: laborant
          default: true
          welcome: "-"
      resources:
        cpuCount: 2
        ramSize: 2G
    - name: node-02
      users:
        - name: root
        - name: laborant
          default: true
          welcome: "-"
      resources:
        cpuCount: 2
        ramSize: 2G
    - name: node-03
      users:
        - name: root
        - name: laborant
          default: true
          welcome: "-"
  tabs:
    - id: terminal-node-01
      kind: terminal
      name: node-01
      machine: node-01
    - id: terminal-node-02
      kind: terminal
      name: node-02
      machine: node-02
    - id: terminal-node-03
      kind: terminal
      name: node-03
      machine: node-03

```

(Notice there is one less machine listed)
