### ISSUE TITLE
Playground web page tab feature seems to be broken

### ISSUE THREAD

**Issue by sagikazarmark** [iximiuz/labs#19]
When trying to push a playground with the following tab:

```yaml
    - kind: web-page
      name: Daggerverse
      url: https://daggerverse.dev
```

Validation fails with the following error:

```
labctl: Couldn't update playground: request failed with status 400: {"error":"Invalid playground manifest: web-page tab's 'url' attribute is required."}.
```

When adding a web page tab through the UI, the resulting manifest looks like this:

```yaml
        - id: web-page-z9zm0udfl3f
          kind: web-page
          name: Daggerverse
          machine: docker
```
