### ISSUE TITLE
Automatically download files

### ISSUE THREAD

**Issue by sagikazarmark** [iximiuz/labs#24]
Machine startup files added the ability to create files accessible to init tasks.

It would be cool to expand that functionality to:

- support cloning git repositories
- support downloading and extracting archives

**Comment by rossbachp** [comment]
You can try this directly in your playground environment:

```yaml
tasks:
  init_honeycluster:
    init: true
    machine: dev-machine
    user: laborant
    run: |-
      git clone https://github.com/k8sstormcenter/honeycluster.git
      cd honeycluster
      git checkout 152-implement-bill-of-behaviour-demo-lab 
      make storage kubescape-bob-kind
```
