### ISSUE TITLE
Startup file directory permissions

### ISSUE THREAD

**Issue by sagikazarmark** [iximiuz/labs#42]
When a startup file references a directory that doesn't exist, it is created with rather weird default permissions:

```yaml
        - path: /opt/lesson/etcd.service
          content: |
            ...
          mode: "644"
          owner: root:root
```

```
laborant@etcd:~$ ls -lah /opt
total 16K
drwxr-xr-x  4 root root 4.0K Jun 18 19:06 .
drwxr-xr-x 21 root root 4.0K Jun 18 19:06 ..
drwxr-xr-x  3 root root 4.0K Jun 18 19:06 iximiuz-labs
drwx------  2 root root 4.0K Jun 18 19:06 lesson
```

Would be nice to use 755 instead.
