### ISSUE TITLE
Allow init conditions without initTasks

### ISSUE THREAD

**Issue by sagikazarmark** [iximiuz/labs#47]
Now that init conditions are written to /opt/iximiuz/init-conditions.json, it's possible to write scripts relying on init conditions that aren't executed as init tasks.

Currently, I have to add a bunch of dummy init tasks, otherwise validation fails:

```
    init_cni_flannel:
      init: true
      machine: kubeadm
      user: root
      run: echo
      conditions:
        - key: Default network addon
          value: flannel
    init_cni_canal:
      init: true
      machine: kubeadm
      user: root
      run: echo
      conditions:
        - key: Default network addon
          value: canal
    init_cni_none:
      init: true
      machine: kubeadm
      user: root
      run: echo
      conditions:
        - key: Default network addon
          value: none
```

Would be nice to allow init conditions without actually using them in tasks.

I know that's not the original purpose of init conditions, but they are a great way to further customize playgrounds.
