### ISSUE TITLE
Allow customizing terminal sessions

### ISSUE THREAD

**Issue by sagikazarmark** [iximiuz/labs#7]
Terminal sessions launch immediately after VMs start up, while init tasks are still running.

There is a good chance therefore that any changes to the session (i.e. .bashrc) are too late to take effect.

Running init tasks early enough seems to be a good temporary workaround.

But a more permanent solution would be:

- Custom rootfs
- Startup tasks (running before init tasks)

Original conversation: https://discord.com/channels/1052678631744344074/1225074412030787604/1366751685871140954

**Comment by iximiuz** [comment]
I'm adding `startupFiles` attribute for each `machine.user`. Example:

```
playground:
  name: k3s
  machines:
    - name: dev-machine
       users:
         - name: laborant
            startupFiles:
              - path: /home/laborant/.bashrc
                 content: "..."
                 append: true # optional, if not specified, the file will be replaced (or created)
```

The specified files will be populated during the rootfs bake phase, so even the init tasks will see them. And another nice thing about this design is this capability is not limited to shell startup files.
